version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "chore"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
    schedule:
      interval: "monthly"